# Site settings
title: "Elliott Wen"
description: "Elliott Wen Ph.should"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Elliott Wen"
resume_title:                   "Hello World!"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jq.elliott.wen@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
resume_contact_address:         "70 Symonds Street, Grafton, Auckland, New Zealand"

resume_header_contact_info:     "70 Symonds Street, Grafton, Auckland, New Zealand • jq.elliott.wen@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a computer scientist with broad research interests, including Mobile Sensing, Software Engineering, and Computer Networking. I am currently working as a Research Fellow at The University of Auckland. During breaks, I love exploring compilers, operating system kernels, and RISC-V CPUs. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/elliott-wen"
  resume_scholar_url:           "https://scholar.google.com/citations?user=0mULezkAAAAJ&hl=en"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
